"""migration

Revision ID: 41db93229723
Revises: 4e8f85bb78c9
Create Date: 2025-08-25 12:10:30.307111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41db93229723'
down_revision: Union[str, Sequence[str], None] = '4e8f85bb78c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.drop_column('users', 'update_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('update_at', sa.DATETIME(), nullable=False))
    op.drop_column('users', 'updated_at')
    # ### end Alembic commands ###
